# Generated by Django 2.1.1 on 2018-10-26 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181025_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='Foto',
            field=models.FileField(blank='True', null='True', upload_to='Fotos/'),
            preserve_default='True',
        ),
    ]
