# Generated by Django 2.1.1 on 2018-10-26 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_mascota_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='Foto',
            field=models.FileField(blank='True', null='True', upload_to='Mascota/'),
        ),
    ]
