# Generated by Django 2.1.2 on 2018-11-21 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='Foto',
            field=models.FileField(blank='True', null='True', upload_to='Mascota'),
        ),
    ]
